// start_stations
let start_stations = [
  {
    "name":"宜山路站",
    "lnglat":['经度','纬度'],
    "busNum":"3",
    "lines":"03路、04路",
    "stationId":"1"
  },
  {
    "name":"江月路站",
    "lnglat":['经度','纬度'],
    "busNum":"2",
    "lines":"05路、06路",
    "stationId":"2"
  },
  {
    "name":"上海火车站",
    "lnglat":['经度','纬度'],
    "busNum":"4",
    "lines":"01路、02路",
    "stationId":"3"
  }
];

// start_offices
let start_offices = [
  {
    "name":"一公司二车队",
    "lnglat":['经度','纬度'],
  },
  {
    "name":"二公司二车队",
    "lnglat":['经度','纬度'],
  },
  {
    "name":"三公司二车队",
    "lnglat":['经度','纬度'],
  }
];

// start_buses
let start_buses = [
  {
    "vno":"S1L-031G",
    "station":"上海火车站",
    "line":"01路",
    "company":"一公司",
    "stationId":"1"
  },
  {
    "vno":"S1L-032G",
    "station":"上海火车站",
    "line":"01路",
    "company":"一公司",
    "stationId":"1"
  },
  {
    "vno":"S1L-033G",
    "station":"上海火车站",
    "line":"01路",
    "company":"一公司",
    "stationId":"1"
  },
  {
    "vno":"S1L-034G",
    "station":"上海火车站",
    "line":"02路",
    "company":"一公司",
    "stationId":"1"
  },
  {
    "vno":"S2L-035G",
    "station":"宜山路站",
    "line":"03路",
    "company":"二公司",
    "stationId":"2"
  },
  {
    "vno":"S2L-036G",
    "station":"宜山路站",
    "line":"03路",
    "company":"二公司",
    "stationId":"2"
  },
  {
    "vno":"S2L-037G",
    "station":"宜山路站",
    "line":"04路",
    "company":"二公司",
    "stationId":"2"
  },
  {
    "vno":"S3L-038G",
    "vno":"S3L-038G",
    "station":"江月路站",
    "line":"05路",
    "company":"三公司",
    "stationId":"3"
  },
  {
    "vno":"S3L-039G",
    "station":"江月路站",
    "line":"06路",
    "company":"三公司",
    "stationId":"3"
  }
];

// ***********************************************************************

// end_stations
let end_stations = [
  {
    "name":"鲁班路站",
    "lnglat":['经度','纬度'],
    "busNum":"3",
    "lines":"01路",
    "stationId":"1"
  },
  {
    "name":"成山路站",
    "lnglat":['经度','纬度'],
    "busNum":"3",
    "lines":"03路、04路",
    "stationId":"2"
  },
  {
    "name":"沈杜公路",
    "lnglat":['经度','纬度'],
    "busNum":"2",
    "lines":"06路、07路",
    "stationId":"3"
  }
];

// end_offices
let end_offices = [
  {
    "name":"三公司一车队",
    "lnglat":['经度','纬度'],
  },
  {
    "name":"五公司一车队",
    "lnglat":['经度','纬度'],
  }
];

// end_buses
let end_buses = [
  {
    "vno":"L1L-100S",
    "station":"鲁班路站",
    "line":"01路",
    "company":"三公司",
    "stationId":"1"
  },
  {
    "vno":"L1L-101S",
    "station":"鲁班路站",
    "line":"01路",
    "company":"三公司",
    "stationId":"1"
  },
  {
    "vno":"L1L-102S",
    "station":"鲁班路站",
    "line":"01路",
    "company":"三公司",
    "stationId":"1"
  },
  {
    "vno":"L2L-103S",
    "station":"成山路站",
    "line":"03路",
    "company":"五公司",
    "stationId":"2"
  },
  {
    "vno":"L2L-104S",
    "station":"成山路站",
    "line":"03路",
    "company":"五公司",
    "stationId":"2"
  },
  {
    "vno":"L2L-105S",
    "station":"成山路站",
    "line":"04路",
    "company":"五公司",
    "stationId":"2"
  },
  {
    "vno":"L3L-106S",
    "station":"沈杜公路",
    "line":"06路",
    "company":"三公司",
    "stationId":"33"
  },
  {
    "vno":"L3L-107S",
    "station":"沈杜公路",
    "line":"07路",
    "company":"三公司",
    "stationId":"3"
  }
];

// ***********************************************************************

let analog_data = {
	"uid":"123456",
	"itemName":"轨交1号线应急支援",
	"line":"1号线人民广场",
	"createTime":"07.20 08:00",
	"beginStation":"人民广场",
	"beginPoint":"121.32321,32.325678",
	"beginRange":"3",
	"endStation":"上海过车站",
	"endPoint":"121.32301,32.325631",
  "endRange":"2",
  // "lineCode":'0802', //加线路编号
  // "endTime":"-",  //加结束时间
	//起点信息
	"begin":{
    "companyNum":"3",
    "officeNum":"2",
    "stationNum":"3",
    "lineNum":"6",
    "busNum":"15",
    "stations":start_stations,
    "offices":start_offices,
    "buses":start_buses
  },
  //终点信息
  "end":{
    "companyNum":"3",
    "officeNum":"2",
    "stationNum":"3",
    "lineNum":"6",
    "busNum":"15",
    "stations":end_stations,
    "offices":end_offices,
    "buses":end_buses
  }
}

// *************************************************************
let analog_data_2 = [
	{
		"company":"巴适一公司",		
		"name":"姓名姓名姓名",				
		"job":"岗位任务描述某个地点或跟车",
		"office":"职职位职位位职职位职位位",
		"radioCode":"651515611565515616515616156",
    "itemName":"预案名去去"
  },
	{
		"company":"巴适一公司",		
		"name":"姓名姓名姓名",				
		"job":"岗位任务描述某个地点或跟车",
		"office":"职职位职位位职职位职位位",
		"radioCode":"651515611565515616515616156",
    "itemName":"预案名去去"
  },
  {
		"company":"巴适一公司",		
		"name":"姓名姓名姓名",				
		"job":"岗位任务描述某个地点或跟车",
		"office":"职职位职位位职职位职位位",
		"radioCode":"651515611565515616515616156",
    "itemName":"预案名去去"
  },
  {
		"company":"巴适一公司",		
		"name":"姓名姓名姓名",				
		"job":"岗位任务描述某个地点或跟车",
		"office":"职职位职位位职职位职位位",
		"radioCode":"651515611565515616515616156",
    "itemName":"预案名去去"
  },
  {
		"company":"巴适一公司",		
		"name":"姓名姓名姓名",				
		"job":"岗位任务描述某个地点或跟车",
		"office":"职职位职位位职职位职位位",
		"radioCode":"651515611565515616515616156",
    "itemName":"预案名去去"
  },
  {
		"company":"巴适一公司",		
		"name":"姓名姓名姓名",				
		"job":"岗位任务描述某个地点或跟车",
		"office":"职职位职位位职职位职位位",
		"radioCode":"651515611565515616515616156",
    "itemName":"预案名去"
  },
  {
		"company":"巴适一公司",		
		"name":"姓名姓名姓名",				
		"job":"岗位任务描述某个地点或跟车",
		"office":"职职位职位位职职位职位位",
		"radioCode":"651515611565515616515616156",
    "itemName":"预案名去"
  },
  {
		"company":"巴适一公司",		
		"name":"姓名姓名姓名",				
		"job":"岗位任务描述某个地点或跟车",
		"office":"职职位职位位职职位职位位",
		"radioCode":"651515611565515616515616156",
    "itemName":"预案名去"
  },
  {
		"company":"巴适一公司",		
		"name":"姓名姓名姓名",				
		"job":"岗位任务描述某个地点或跟车",
		"office":"职职位职位位职职位职位位",
		"radioCode":"651515611565515616515616156",
    "itemName":"预案名去"
	}
]

export { analog_data, analog_data_2 };